name: auto-cpufreq
base: core18
version: '1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Automatic CPU speed & power optimizer for Linux
description: |
  Automatic CPU speed & power optimizer for Linux based on active
  monitoring of laptop's battery state, CPU usage and system load.
  Ultimately allowing you to improve battery life without making
  any compromises.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  auto-cpufreq:
    # See 'snapcraft plugins'
    plugin: python
    python-version: python3
    source: .
    #stage-packages:
    #  - python3-pip
    #  - python3-dev
    #python-packages:
    #  - psutil
    #  - click
    #  - distro
    #  - power

  deploy-cpufrectl:
    plugin: dump
    source: scripts
    organize:
      cpufreqctl.sh: usr/bin/cpufreqctl

# ToDo: remove scripts/daemon
  # deploy-demon:
  #   plugin: dump
  #   source: scripts
  #   organize:
  #     daemon.sh: usr/bin/daemon

apps:
  auto-cpufreq:
    command: bin/auto-cpufreq
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      PKG_MARKER: SNAP
  auto-cpufreq-service:
    command: bin/auto-cpufreq --daemon 2>&1 | tee -a /var/log/auto-cpufreq.log
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      PKG_MARKER: SNAP
    daemon: simple
    